// Code generated by config233. DO NOT EDIT.
// Source: FishingWeaponConfig.xlsx

package generated

// FishingWeaponConfig 配置结构体
type FishingWeaponConfig struct {
	Id int `json:"id"`
	UnlockCostGoldCount int `json:"unlockCostGoldCount"`
	SkillId int `json:"skillId"`
}
