// Code generated by config233. DO NOT EDIT.
// Source: FishingKvConfig.xlsx

package generated

import "github.com/neko233-com/config233-go/internal/config233"

// FishingKvConfig 配置结构体
type FishingKvConfig struct {
	Id    string `json:"id"`
	Value string `json:"value"`
}

// Ensure FishingKvConfig implements IKvConfig interface
var _ config233.IKvConfig = (*FishingKvConfig)(nil)

// GetValue 实现 IKvConfig 接口
func (c *FishingKvConfig) GetValue() string {
	return c.Value
}
