// Code generated by config233. DO NOT EDIT.
// Source: GodLvUpConfig.xlsx

package generated

// GodLvUpConfig 配置结构体
type GodLvUpConfig struct {
	Id                     int    `json:"id"`
	LvUpConditionText      string `json:"lvUpConditionText"`
	CostItemText           string `json:"costItemText"`
	LvUpNeedWaitTimeSecond int64  `json:"lvUpNeedWaitTimeSecond"`
	UnlockOtherBuildingIds []int  `json:"unlockOtherBuildingIds"`
}
