// Code generated by config233. DO NOT EDIT.
// Source: TestKvConfig.xlsx

package generated

import "github.com/neko233-com/config233-go/internal/config233"

// TestKvConfig 配置结构体
type TestKvConfig struct {
	Id    string `json:"id"`
	Value string `json:"value"`
}

// Ensure TestKvConfig implements IKvConfig interface
var _ config233.IKvConfig = (*TestKvConfig)(nil)

// GetValue 实现 IKvConfig 接口
func (c *TestKvConfig) GetValue() string {
	return c.Value
}
